ALTER TABLE users
ADD COLUMN bio TEXT,
ADD COLUMN is_id_verified BOOLEAN DEFAULT FALSE,
ADD COLUMN address_line1 VARCHAR(255),
ADD COLUMN address_line2 VARCHAR(255),
ADD COLUMN city VARCHAR(100),
ADD COLUMN state VARCHAR(50),
ADD COLUMN zip_code VARCHAR(20),
ADD COLUMN social_link VARCHAR(255);
